[package]
name = "ecs"
version = "0.1.0"
authors = ["lostr <alexisgougaut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
bitset = "0.1.2"